### ISSUE TITLE
[UI] Create a random password generator

### ISSUE THREAD

**Issue by Deveesh-Shetty** [Deveesh-Shetty/CSS-Is-Fun#18]
Use HTML, CSS, and JavaScript to create a Random Password Generator.

Feel free to ask for any help!

**Comment by AKASH-PRASAD7** [comment]
Hey, I would like to work on this issue, would be great if you assign me this issue.

**Comment by Deveesh-Shetty** [comment]
Yeah sure! Assign it to you
